# K=40 Flow+TRL best-param follow-up
# source IDM=0.768 ACTOR=0.656; horizon=40; final_eval_N=2
env_name: cube-single-play-v0
run_group: flow_trl_k40_best_cs_g10_en2
train_epochs: 600
log_every_n_epochs: 10
save_every_n_epochs: 100
horizon: 40
eval_freq: 100
eval_episodes_per_task: 10
final_eval_episodes_per_task: 25
dynamics:
  subgoal_distribution: flow
  subgoal_stochastic_loss: mse
  subgoal_num_samples: 1
  subgoal_value_gap_scale: 10.0
  subgoal_value_weight_max: 5.0
  actor_p_curgoal: 0.0
  actor_p_trajgoal: 1.0
  actor_p_randomgoal: 0.0
  actor_geom_sample: false
  subgoal_temperature: 1.0
  subgoal_eval_seed: 0
  dynamics_N: 40
  subgoal_steps: 40
  subgoal_eval_num_samples: 1
critic_agent:
  full_chunk_horizon: 40
  discount: 0.99
  value_distance_weight_power: 0.7
  value_p_curgoal: 0.0
  value_p_trajgoal: 1.0
  value_p_randomgoal: 0.0
actor:
  spi_tau: 5.0
batch_size: 1024
final_eval_subgoal_eval_num_samples: '2'
